local M = {}

function M.setup(c)
  local groups = {
    -- Editor UI
    Normal        = { fg = c.fg,      bg = c.bg },
    NormalFloat   = { fg = c.fg,      bg = c.bg_soft },
    SignColumn    = { bg = c.bg },
    CursorLine    = { bg = c.curor_line  },
    CursorLineNr  = { fg = c.fg },
    LineNr        = { fg = c.comment },
    VertSplit     = { fg = c.bg_ui,   bg = c.bg },
    StatusLine    = { fg = c.fg,      bg = c.bg_ui },
    StatusLineNC  = { fg = c.comment, bg = c.bg_ui },
    Pmenu         = { fg = c.fg,      bg = c.bg_soft },
    PmenuSel      = { fg = c.fg,      bg = c.bg_ui },
    Visual        = { bg =  c.visual },
    Search        = { fg = c.bg,      bg = c.type },
    IncSearch     = { fg = c.bg,      bg = c.keyword },
    MatchParen    = { fg = c.keyword, bold = true },

    -- Base syntax (define colors here once)
    Comment      = { fg = c.comment, italic = true },
    Keyword      = { fg = c.keyword },
    Statement    = { fg = c.keyword },
    Conditional  = { fg = c.keyword },
    Repeat       = { fg = c.keyword },
    Label        = { fg = c.keyword },
    Exception    = { fg = c.keyword },
    PreProc      = { fg = c.keyword },
    Include      = { fg = c.keyword },
    Define       = { fg = c.keyword },
    StorageClass = { fg = c.keyword },
    Type         = { fg = c.type },
    Structure    = { fg = c.type },
    Typedef      = { fg = c.type },
    Constant     = { fg = c.constant },
    Macro        = { fg = c.constant },
    Number       = { fg = c.constant },
    Boolean      = { fg = c.constant },
    Float        = { fg = c.constant },
    String       = { fg = c.constant },
    Character    = { fg = c.constant },
    Identifier   = { fg = c.fg },
    Function     = { fg = c.fg },
    Operator     = { fg = c.fg },
    Special      = { fg = c.fg },
    Delimiter    = { fg = c.fg },

    -- Treesitter links to base syntax (no color duplication)
    ["@comment"]                   = { link = "Comment" },
    ["@keyword"]                   = { link = "Keyword" },
    ["@keyword.function"]          = { link = "Keyword" },
    ["@keyword.return"]            = { link = "Keyword" },
    ["@keyword.operator"]          = { link = "Operator" },
    ["@keyword.import"]            = { link = "Include" },
    ["@keyword.modifier"]          = { link = "Keyword" },
    ["@keyword.repeat"]            = { link = "Repeat" },
    ["@keyword.conditional"]       = { link = "Conditional" },
    ["@keyword.exception"]         = { link = "Exception" },
    ["@keyword.directive"]         = { link = "Define" },
    ["@keyword.directive.define"]  = { link = "Define" },
    ["@type"]                      = { link = "Type" },
    ["@type.builtin"]              = { link = "Type" },
    ["@constant"]                  = { link = "Constant" },
    ["@constant.builtin"]          = { link = "Constant" },
    ["@boolean"]                   = { link = "Boolean" },
    ["@number"]                    = { link = "Number" },
    ["@number.float"]              = { link = "Number" },
    ["@string"]                    = { link = "String" },
    ["@variable"]                  = { link = "Identifier" },
    ["@variable.builtin"]          = { link = "Identifier" },
    ["@variable.member"]           = { link = "Identifier" },
    ["@variable.parameter"]        = { link = "Identifier" },
    ["@function"]                  = { link = "Function" },
    ["@function.builtin"]          = { link = "Function" },
    ["@function.call"]             = { link = "Function" },
    ["@function.method"]           = { link = "Function" },
    ["@function.method.call"]      = { link = "Function" },
    ["@constructor"]               = { link = "Function" },
    ["@operator"]                  = { link = "Operator" },
    ["@punctuation.delimiter"]     = { link = "Delimiter" },
    ["@punctuation.bracket"]       = { link = "Delimiter" },
    ["@module"]                    = { link = "Type" },
    ["@attribute"]                 = { link = "Keyword" },

    -- LSP Diagnostics
    DiagnosticError          = { fg = c.keyword },
    DiagnosticWarn           = { fg = c.type },
    DiagnosticInfo           = { fg = c.fg },
    DiagnosticHint           = { fg = c.comment },
    DiagnosticUnderlineError = { undercurl = true, sp = c.keyword },
    DiagnosticUnderlineWarn  = { undercurl = true, sp = c.type },

    -- Bufferline
    BufferLineFill             = { bg = c.bg_soft },
    BufferLineBackground       = { fg = c.comment, bg = c.bg_soft },
    BufferLineBufferSelected   = { fg = c.fg,      bg = c.bg, bold = true },
    BufferLineBufferVisible    = { fg = c.comment, bg = c.bg_soft },
    BufferLineSeparator        = { fg = c.bg,      bg = c.bg_soft },
    BufferLineSeparatorSelected = { fg = c.bg,     bg = c.bg },
    BufferLineIndicatorSelected = { fg = c.keyword, bg = c.bg },
    BufferLineModified         = { fg = c.type,    bg = c.bg_soft },
    BufferLineModifiedSelected = { fg = c.constant, bg = c.bg },
    BufferLineCloseButton      = { fg = c.comment, bg = c.bg_soft },
    BufferLineCloseButtonSelected = { fg = c.keyword, bg = c.bg },
    BufferLineTab              = { fg = c.comment, bg = c.bg_soft },
    BufferLineTabSelected      = { fg = c.fg,      bg = c.bg },

    -- -- NvimTree
    NvimTreeNormal           = { fg = c.fg,      bg = c.bg_soft },
    NvimTreeNormalNC         = { fg = c.fg,      bg = c.bg_soft },
    NvimTreeRootFolder       = { fg = c.keyword, bold = true },
    NvimTreeFolderName       = { fg = c.fg },
    NvimTreeFolderIcon       = { fg = c.type },
    NvimTreeOpenedFolderName = { fg = c.fg },
    NvimTreeEmptyFolderName  = { fg = c.comment },
    NvimTreeIndentMarker     = { fg = c.bg_ui },
    NvimTreeVertSplit        = { fg = c.bg_soft, bg = c.bg_soft },
    NvimTreeWinSeparator     = { fg = c.bg_soft, bg = c.bg_soft },
    NvimTreeStatusLine       = { fg = c.bg_soft, bg = c.bg_soft },
    NvimTreeStatusLineNC     = { fg = c.bg_soft, bg = c.bg_soft },
    
    -- files
    NvimTreeFileNew          = { fg = c.constant },
    NvimTreeFileDeleted      = { fg = c.keyword },
    NvimTreeFileDirty        = { fg = c.type },
    NvimTreeFileStaged       = { fg = c.constant },
    NvimTreeFileMerge        = { fg = c.type },
    NvimTreeFileRenamed      = { fg = c.constant },
    NvimTreeSymlink          = { fg = c.type },
    NvimTreeExecFile         = { fg = c.constant },
    NvimTreeSpecialFile      = { fg = c.fg },
    NvimTreeImageFile        = { fg = c.fg },
    
    -- git
    NvimTreeGitDirty         = { fg = c.type },
    NvimTreeGitStaged        = { fg = c.constant },
    NvimTreeGitMerge         = { fg = c.type },
    NvimTreeGitRenamed       = { fg = c.constant },
    NvimTreeGitNew           = { fg = c.constant },
    NvimTreeGitDeleted       = { fg = c.keyword },
    NvimTreeGitIgnored       = { fg = c.comment },
  }

  for group, opts in pairs(groups) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

return M
